version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/opt/app/api
  db:
    image: postgres
    networks:
      new:
        aliases:
          - database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432"
  migrate:
    image: migrate/migrate
    networks:
        - new
    volumes:
        - .:/migrations
    command: [ "-path", "./migrations/postgres/", "-database",  "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable", "up"]
    links:
        - db
